/**
 * GetCandy
 * The GetCandy API
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The AssetSimple model module.
 * @module model/AssetSimple
 * @version 1.0.0
 */
class AssetSimple {
    /**
     * Constructs a new <code>AssetSimple</code>.
     * @alias module:model/AssetSimple
     */
    constructor() { 
        
        AssetSimple.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>AssetSimple</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/AssetSimple} obj Optional instance to populate.
     * @return {module:model/AssetSimple} The populated <code>AssetSimple</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new AssetSimple();

            if (data.hasOwnProperty('thumbnail_url')) {
                obj['thumbnail_url'] = ApiClient.convertToType(data['thumbnail_url'], 'String');
            }
            if (data.hasOwnProperty('thumbnail')) {
                obj['thumbnail'] = ApiClient.convertToType(data['thumbnail'], 'String');
            }
            if (data.hasOwnProperty('url')) {
                obj['url'] = ApiClient.convertToType(data['url'], 'String');
            }
            if (data.hasOwnProperty('filename')) {
                obj['filename'] = ApiClient.convertToType(data['filename'], 'String');
            }
            if (data.hasOwnProperty('path')) {
                obj['path'] = ApiClient.convertToType(data['path'], 'String');
            }
        }
        return obj;
    }


}

/**
 * @member {String} thumbnail_url
 */
AssetSimple.prototype['thumbnail_url'] = undefined;

/**
 * @member {String} thumbnail
 */
AssetSimple.prototype['thumbnail'] = undefined;

/**
 * @member {String} url
 */
AssetSimple.prototype['url'] = undefined;

/**
 * @member {String} filename
 */
AssetSimple.prototype['filename'] = undefined;

/**
 * @member {String} path
 */
AssetSimple.prototype['path'] = undefined;






export default AssetSimple;

