/**
 * GetCandy
 * The GetCandy API
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@getcandy.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The AssetDetachBody model module.
 * @module model/AssetDetachBody
 * @version 0.9.0
 */
class AssetDetachBody {
    /**
     * Constructs a new <code>AssetDetachBody</code>.
     * @alias module:model/AssetDetachBody
     */
    constructor() { 
        
        AssetDetachBody.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>AssetDetachBody</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/AssetDetachBody} obj Optional instance to populate.
     * @return {module:model/AssetDetachBody} The populated <code>AssetDetachBody</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new AssetDetachBody();

            if (data.hasOwnProperty('attributes')) {
                obj['attributes'] = ApiClient.convertToType(data['attributes'], [Object]);
            }
        }
        return obj;
    }


}

/**
 * attributeId => position
 * @member {Array.<Object>} attributes
 */
AssetDetachBody.prototype['attributes'] = undefined;






export default AssetDetachBody;

