/**
 * GetCandy
 * The GetCandy API
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import AssetTransform from './AssetTransform';
import AssetTransformCollectionAllOf from './AssetTransformCollectionAllOf';
import Links from './Links';
import PaginatedResponse from './PaginatedResponse';
import Pagination from './Pagination';

/**
 * The AssetTransformCollection model module.
 * @module model/AssetTransformCollection
 * @version 1.0.0
 */
class AssetTransformCollection {
    /**
     * Constructs a new <code>AssetTransformCollection</code>.
     * @alias module:model/AssetTransformCollection
     * @extends module:model/PaginatedResponse
     * @implements module:model/AssetTransformCollectionAllOf
     * @implements module:model/PaginatedResponse
     */
    constructor() { 
        AssetTransformCollectionAllOf.initialize(this);PaginatedResponse.initialize(this);
        AssetTransformCollection.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>AssetTransformCollection</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/AssetTransformCollection} obj Optional instance to populate.
     * @return {module:model/AssetTransformCollection} The populated <code>AssetTransformCollection</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new AssetTransformCollection();
            PaginatedResponse.constructFromObject(data, obj);
            AssetTransformCollectionAllOf.constructFromObject(data, obj);
            PaginatedResponse.constructFromObject(data, obj);

            if (data.hasOwnProperty('data')) {
                obj['data'] = ApiClient.convertToType(data['data'], [AssetTransform]);
            }
        }
        return obj;
    }


}

/**
 * @member {Array.<module:model/AssetTransform>} data
 */
AssetTransformCollection.prototype['data'] = undefined;


// Implement AssetTransformCollectionAllOf interface:
/**
 * @member {Array.<module:model/AssetTransform>} data
 */
AssetTransformCollectionAllOf.prototype['data'] = undefined;
// Implement PaginatedResponse interface:
/**
 * @member {module:model/Links} links
 */
PaginatedResponse.prototype['links'] = undefined;
/**
 * @member {module:model/Pagination} meta
 */
PaginatedResponse.prototype['meta'] = undefined;




export default AssetTransformCollection;

