/**
 * GetCandy
 * The GetCandy API
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@getcandy.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The AssociationGroup model module.
 * @module model/AssociationGroup
 * @version 0.9.0
 */
class AssociationGroup {
    /**
     * Constructs a new <code>AssociationGroup</code>.
     * @alias module:model/AssociationGroup
     */
    constructor() { 
        
        AssociationGroup.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>AssociationGroup</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/AssociationGroup} obj Optional instance to populate.
     * @return {module:model/AssociationGroup} The populated <code>AssociationGroup</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new AssociationGroup();

            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'String');
            }
            if (data.hasOwnProperty('name')) {
                obj['name'] = ApiClient.convertToType(data['name'], 'String');
            }
            if (data.hasOwnProperty('handle')) {
                obj['handle'] = ApiClient.convertToType(data['handle'], 'String');
            }
        }
        return obj;
    }


}

/**
 * @member {String} id
 */
AssociationGroup.prototype['id'] = undefined;

/**
 * @member {String} name
 */
AssociationGroup.prototype['name'] = undefined;

/**
 * @member {String} handle
 */
AssociationGroup.prototype['handle'] = undefined;






export default AssociationGroup;

