/**
 * GetCandy
 * The GetCandy API
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The AttributeData model module.
 * @module model/AttributeData
 * @version 1.0.0
 */
class AttributeData {
    /**
     * Constructs a new <code>AttributeData</code>.
     * @alias module:model/AttributeData
     */
    constructor() { 
        
        AttributeData.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>AttributeData</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/AttributeData} obj Optional instance to populate.
     * @return {module:model/AttributeData} The populated <code>AttributeData</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new AttributeData();

            if (data.hasOwnProperty('attribute_data')) {
                obj['attribute_data'] = ApiClient.convertToType(data['attribute_data'], Object);
            }
        }
        return obj;
    }


}

/**
 * @member {Object} attribute_data
 */
AttributeData.prototype['attribute_data'] = undefined;






export default AttributeData;

