/**
 * GetCandy
 * The GetCandy API
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import DiscountsDiscountIdRewardsData from './DiscountsDiscountIdRewardsData';

/**
 * The DiscountsDiscountIdRewards model module.
 * @module model/DiscountsDiscountIdRewards
 * @version 1.0.0
 */
class DiscountsDiscountIdRewards {
    /**
     * Constructs a new <code>DiscountsDiscountIdRewards</code>.
     * @alias module:model/DiscountsDiscountIdRewards
     */
    constructor() { 
        
        DiscountsDiscountIdRewards.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>DiscountsDiscountIdRewards</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/DiscountsDiscountIdRewards} obj Optional instance to populate.
     * @return {module:model/DiscountsDiscountIdRewards} The populated <code>DiscountsDiscountIdRewards</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new DiscountsDiscountIdRewards();

            if (data.hasOwnProperty('data')) {
                obj['data'] = DiscountsDiscountIdRewardsData.constructFromObject(data['data']);
            }
        }
        return obj;
    }


}

/**
 * @member {module:model/DiscountsDiscountIdRewardsData} data
 */
DiscountsDiscountIdRewards.prototype['data'] = undefined;






export default DiscountsDiscountIdRewards;

