/**
 * GetCandy
 * The GetCandy API
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The InlineResponse42210 model module.
 * @module model/InlineResponse42210
 * @version 1.0.0
 */
class InlineResponse42210 {
    /**
     * Constructs a new <code>InlineResponse42210</code>.
     * @alias module:model/InlineResponse42210
     */
    constructor() { 
        
        InlineResponse42210.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>InlineResponse42210</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/InlineResponse42210} obj Optional instance to populate.
     * @return {module:model/InlineResponse42210} The populated <code>InlineResponse42210</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new InlineResponse42210();

            if (data.hasOwnProperty('name')) {
                obj['name'] = ApiClient.convertToType(data['name'], ['String']);
            }
            if (data.hasOwnProperty('url')) {
                obj['url'] = ApiClient.convertToType(data['url'], ['String']);
            }
            if (data.hasOwnProperty('stock')) {
                obj['stock'] = ApiClient.convertToType(data['stock'], ['String']);
            }
            if (data.hasOwnProperty('family_id')) {
                obj['family_id'] = ApiClient.convertToType(data['family_id'], ['String']);
            }
            if (data.hasOwnProperty('price')) {
                obj['price'] = ApiClient.convertToType(data['price'], ['String']);
            }
            if (data.hasOwnProperty('sku')) {
                obj['sku'] = ApiClient.convertToType(data['sku'], ['String']);
            }
        }
        return obj;
    }


}

/**
 * @member {Array.<String>} name
 */
InlineResponse42210.prototype['name'] = undefined;

/**
 * @member {Array.<String>} url
 */
InlineResponse42210.prototype['url'] = undefined;

/**
 * @member {Array.<String>} stock
 */
InlineResponse42210.prototype['stock'] = undefined;

/**
 * @member {Array.<String>} family_id
 */
InlineResponse42210.prototype['family_id'] = undefined;

/**
 * @member {Array.<String>} price
 */
InlineResponse42210.prototype['price'] = undefined;

/**
 * @member {Array.<String>} sku
 */
InlineResponse42210.prototype['sku'] = undefined;






export default InlineResponse42210;

