/**
 * GetCandy
 * The GetCandy API
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@getcandy.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The InlineObject22 model module.
 * @module model/InlineObject22
 * @version 0.9.0
 */
class InlineObject22 {
    /**
     * Constructs a new <code>InlineObject22</code>.
     * @alias module:model/InlineObject22
     * @param categories {Array.<String>} Array of category ID's
     */
    constructor(categories) { 
        
        InlineObject22.initialize(this, categories);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, categories) { 
        obj['categories'] = categories;
    }

    /**
     * Constructs a <code>InlineObject22</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/InlineObject22} obj Optional instance to populate.
     * @return {module:model/InlineObject22} The populated <code>InlineObject22</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new InlineObject22();

            if (data.hasOwnProperty('categories')) {
                obj['categories'] = ApiClient.convertToType(data['categories'], ['String']);
            }
        }
        return obj;
    }


}

/**
 * Array of category ID's
 * @member {Array.<String>} categories
 */
InlineObject22.prototype['categories'] = undefined;






export default InlineObject22;

