/**
 * GetCandy
 * The GetCandy API
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@getcandy.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import DiscountsChannels from './DiscountsChannels';
import DiscountsName from './DiscountsName';

/**
 * The InlineObject9 model module.
 * @module model/InlineObject9
 * @version 0.9.0
 */
class InlineObject9 {
    /**
     * Constructs a new <code>InlineObject9</code>.
     * @alias module:model/InlineObject9
     * @param name {module:model/DiscountsName} 
     */
    constructor(name) { 
        
        InlineObject9.initialize(this, name);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, name) { 
        obj['name'] = name;
    }

    /**
     * Constructs a <code>InlineObject9</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/InlineObject9} obj Optional instance to populate.
     * @return {module:model/InlineObject9} The populated <code>InlineObject9</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new InlineObject9();

            if (data.hasOwnProperty('start_at')) {
                obj['start_at'] = ApiClient.convertToType(data['start_at'], 'Date');
            }
            if (data.hasOwnProperty('end_at')) {
                obj['end_at'] = ApiClient.convertToType(data['end_at'], 'Date');
            }
            if (data.hasOwnProperty('name')) {
                obj['name'] = DiscountsName.constructFromObject(data['name']);
            }
            if (data.hasOwnProperty('uses')) {
                obj['uses'] = ApiClient.convertToType(data['uses'], 'Number');
            }
            if (data.hasOwnProperty('status')) {
                obj['status'] = ApiClient.convertToType(data['status'], 'Boolean');
            }
            if (data.hasOwnProperty('channels')) {
                obj['channels'] = ApiClient.convertToType(data['channels'], [DiscountsChannels]);
            }
        }
        return obj;
    }


}

/**
 * @member {Date} start_at
 */
InlineObject9.prototype['start_at'] = undefined;

/**
 * @member {Date} end_at
 */
InlineObject9.prototype['end_at'] = undefined;

/**
 * @member {module:model/DiscountsName} name
 */
InlineObject9.prototype['name'] = undefined;

/**
 * @member {Number} uses
 */
InlineObject9.prototype['uses'] = undefined;

/**
 * @member {Boolean} status
 */
InlineObject9.prototype['status'] = undefined;

/**
 * @member {Array.<module:model/DiscountsChannels>} channels
 */
InlineObject9.prototype['channels'] = undefined;






export default InlineObject9;

