/**
 * GetCandy
 * The GetCandy API
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The InlineObject31 model module.
 * @module model/InlineObject31
 * @version 1.0.0
 */
class InlineObject31 {
    /**
     * Constructs a new <code>InlineObject31</code>.
     * @alias module:model/InlineObject31
     * @param rate {Number} 
     * @param zoneId {String} 
     * @param currencyId {String} 
     */
    constructor(rate, zoneId, currencyId) { 
        
        InlineObject31.initialize(this, rate, zoneId, currencyId);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, rate, zoneId, currencyId) { 
        obj['rate'] = rate;
        obj['zone_id'] = zoneId;
        obj['currency_id'] = currencyId;
    }

    /**
     * Constructs a <code>InlineObject31</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/InlineObject31} obj Optional instance to populate.
     * @return {module:model/InlineObject31} The populated <code>InlineObject31</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new InlineObject31();

            if (data.hasOwnProperty('rate')) {
                obj['rate'] = ApiClient.convertToType(data['rate'], 'Number');
            }
            if (data.hasOwnProperty('zone_id')) {
                obj['zone_id'] = ApiClient.convertToType(data['zone_id'], 'String');
            }
            if (data.hasOwnProperty('currency_id')) {
                obj['currency_id'] = ApiClient.convertToType(data['currency_id'], 'String');
            }
        }
        return obj;
    }


}

/**
 * @member {Number} rate
 */
InlineObject31.prototype['rate'] = undefined;

/**
 * @member {String} zone_id
 */
InlineObject31.prototype['zone_id'] = undefined;

/**
 * @member {String} currency_id
 */
InlineObject31.prototype['currency_id'] = undefined;






export default InlineObject31;

