/**
 * GetCandy
 * The GetCandy API
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The InlineObject41 model module.
 * @module model/InlineObject41
 * @version 1.0.0
 */
class InlineObject41 {
    /**
     * Constructs a new <code>InlineObject41</code>.
     * @alias module:model/InlineObject41
     * @param email {String} 
     */
    constructor(email) { 
        
        InlineObject41.initialize(this, email);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, email) { 
        obj['email'] = email;
    }

    /**
     * Constructs a <code>InlineObject41</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/InlineObject41} obj Optional instance to populate.
     * @return {module:model/InlineObject41} The populated <code>InlineObject41</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new InlineObject41();

            if (data.hasOwnProperty('email')) {
                obj['email'] = ApiClient.convertToType(data['email'], 'String');
            }
            if (data.hasOwnProperty('password')) {
                obj['password'] = ApiClient.convertToType(data['password'], 'String');
            }
            if (data.hasOwnProperty('password_confirmation')) {
                obj['password_confirmation'] = ApiClient.convertToType(data['password_confirmation'], 'String');
            }
        }
        return obj;
    }


}

/**
 * @member {String} email
 */
InlineObject41.prototype['email'] = undefined;

/**
 * @member {String} password
 */
InlineObject41.prototype['password'] = undefined;

/**
 * @member {String} password_confirmation
 */
InlineObject41.prototype['password_confirmation'] = undefined;






export default InlineObject41;

