/**
 * GetCandy
 * The GetCandy API
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The InlineObject21 model module.
 * @module model/InlineObject21
 * @version 1.0.0
 */
class InlineObject21 {
    /**
     * Constructs a new <code>InlineObject21</code>.
     * @alias module:model/InlineObject21
     * @param attributes {Array.<String>} An array of attribute IDs
     */
    constructor(attributes) { 
        
        InlineObject21.initialize(this, attributes);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, attributes) { 
        obj['attributes'] = attributes;
    }

    /**
     * Constructs a <code>InlineObject21</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/InlineObject21} obj Optional instance to populate.
     * @return {module:model/InlineObject21} The populated <code>InlineObject21</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new InlineObject21();

            if (data.hasOwnProperty('attributes')) {
                obj['attributes'] = ApiClient.convertToType(data['attributes'], ['String']);
            }
        }
        return obj;
    }


}

/**
 * An array of attribute IDs
 * @member {Array.<String>} attributes
 */
InlineObject21.prototype['attributes'] = undefined;






export default InlineObject21;

