/**
 * GetCandy
 * The GetCandy API
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@getcandy.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The InlineResponse42214 model module.
 * @module model/InlineResponse42214
 * @version 0.9.0
 */
class InlineResponse42214 {
    /**
     * Constructs a new <code>InlineResponse42214</code>.
     * @alias module:model/InlineResponse42214
     */
    constructor() { 
        
        InlineResponse42214.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>InlineResponse42214</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/InlineResponse42214} obj Optional instance to populate.
     * @return {module:model/InlineResponse42214} The populated <code>InlineResponse42214</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new InlineResponse42214();

            if (data.hasOwnProperty('name')) {
                obj['name'] = ApiClient.convertToType(data['name'], ['String']);
            }
            if (data.hasOwnProperty('type')) {
                obj['type'] = ApiClient.convertToType(data['type'], ['String']);
            }
        }
        return obj;
    }


}

/**
 * @member {Array.<String>} name
 */
InlineResponse42214.prototype['name'] = undefined;

/**
 * @member {Array.<String>} type
 */
InlineResponse42214.prototype['type'] = undefined;






export default InlineResponse42214;

