/**
 * GetCandy
 * The GetCandy API
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@getcandy.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The InlineResponse4229Errors model module.
 * @module model/InlineResponse4229Errors
 * @version 0.9.0
 */
class InlineResponse4229Errors {
    /**
     * Constructs a new <code>InlineResponse4229Errors</code>.
     * @alias module:model/InlineResponse4229Errors
     */
    constructor() { 
        
        InlineResponse4229Errors.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>InlineResponse4229Errors</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/InlineResponse4229Errors} obj Optional instance to populate.
     * @return {module:model/InlineResponse4229Errors} The populated <code>InlineResponse4229Errors</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new InlineResponse4229Errors();

            if (data.hasOwnProperty('from')) {
                obj['from'] = ApiClient.convertToType(data['from'], ['String']);
            }
            if (data.hasOwnProperty('to')) {
                obj['to'] = ApiClient.convertToType(data['to'], ['String']);
            }
        }
        return obj;
    }


}

/**
 * @member {Array.<String>} from
 */
InlineResponse4229Errors.prototype['from'] = undefined;

/**
 * @member {Array.<String>} to
 */
InlineResponse4229Errors.prototype['to'] = undefined;






export default InlineResponse4229Errors;

