/**
 * GetCandy
 * The GetCandy API
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import InlineResponse4229Errors from './InlineResponse4229Errors';

/**
 * The InlineResponse4229 model module.
 * @module model/InlineResponse4229
 * @version 1.0.0
 */
class InlineResponse4229 {
    /**
     * Constructs a new <code>InlineResponse4229</code>.
     * @alias module:model/InlineResponse4229
     */
    constructor() { 
        
        InlineResponse4229.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>InlineResponse4229</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/InlineResponse4229} obj Optional instance to populate.
     * @return {module:model/InlineResponse4229} The populated <code>InlineResponse4229</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new InlineResponse4229();

            if (data.hasOwnProperty('message')) {
                obj['message'] = ApiClient.convertToType(data['message'], 'String');
            }
            if (data.hasOwnProperty('errors')) {
                obj['errors'] = ApiClient.convertToType(data['errors'], [InlineResponse4229Errors]);
            }
        }
        return obj;
    }


}

/**
 * @member {String} message
 */
InlineResponse4229.prototype['message'] = undefined;

/**
 * @member {Array.<module:model/InlineResponse4229Errors>} errors
 */
InlineResponse4229.prototype['errors'] = undefined;






export default InlineResponse4229;

