/**
 * GetCandy
 * The GetCandy API
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The InlineResponse2004DateProducts model module.
 * @module model/InlineResponse2004DateProducts
 * @version 1.0.0
 */
class InlineResponse2004DateProducts {
    /**
     * Constructs a new <code>InlineResponse2004DateProducts</code>.
     * @alias module:model/InlineResponse2004DateProducts
     */
    constructor() { 
        
        InlineResponse2004DateProducts.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>InlineResponse2004DateProducts</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/InlineResponse2004DateProducts} obj Optional instance to populate.
     * @return {module:model/InlineResponse2004DateProducts} The populated <code>InlineResponse2004DateProducts</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new InlineResponse2004DateProducts();

            if (data.hasOwnProperty('product_count')) {
                obj['product_count'] = ApiClient.convertToType(data['product_count'], 'Number');
            }
            if (data.hasOwnProperty('description')) {
                obj['description'] = ApiClient.convertToType(data['description'], 'String');
            }
            if (data.hasOwnProperty('sku')) {
                obj['sku'] = ApiClient.convertToType(data['sku'], 'String');
            }
            if (data.hasOwnProperty('month')) {
                obj['month'] = ApiClient.convertToType(data['month'], 'String');
            }
        }
        return obj;
    }


}

/**
 * @member {Number} product_count
 */
InlineResponse2004DateProducts.prototype['product_count'] = undefined;

/**
 * @member {String} description
 */
InlineResponse2004DateProducts.prototype['description'] = undefined;

/**
 * @member {String} sku
 */
InlineResponse2004DateProducts.prototype['sku'] = undefined;

/**
 * @member {String} month
 */
InlineResponse2004DateProducts.prototype['month'] = undefined;






export default InlineResponse2004DateProducts;

