/**
 * GetCandy
 * The GetCandy API
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@getcandy.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The InlineResponse4221 model module.
 * @module model/InlineResponse4221
 * @version 0.9.0
 */
class InlineResponse4221 {
    /**
     * Constructs a new <code>InlineResponse4221</code>.
     * @alias module:model/InlineResponse4221
     */
    constructor() { 
        
        InlineResponse4221.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>InlineResponse4221</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/InlineResponse4221} obj Optional instance to populate.
     * @return {module:model/InlineResponse4221} The populated <code>InlineResponse4221</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new InlineResponse4221();

            if (data.hasOwnProperty('group_id')) {
                obj['group_id'] = ApiClient.convertToType(data['group_id'], ['String']);
            }
            if (data.hasOwnProperty('name')) {
                obj['name'] = ApiClient.convertToType(data['name'], ['String']);
            }
            if (data.hasOwnProperty('handle')) {
                obj['handle'] = ApiClient.convertToType(data['handle'], ['String']);
            }
        }
        return obj;
    }


}

/**
 * @member {Array.<String>} group_id
 */
InlineResponse4221.prototype['group_id'] = undefined;

/**
 * @member {Array.<String>} name
 */
InlineResponse4221.prototype['name'] = undefined;

/**
 * @member {Array.<String>} handle
 */
InlineResponse4221.prototype['handle'] = undefined;






export default InlineResponse4221;

