/**
 * GetCandy
 * The GetCandy API
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The InlineObject11 model module.
 * @module model/InlineObject11
 * @version 1.0.0
 */
class InlineObject11 {
    /**
     * Constructs a new <code>InlineObject11</code>.
     * @alias module:model/InlineObject11
     * @param name {String} 
     * @param lang {String} 
     * @param iso {String} Unique
     */
    constructor(name, lang, iso) { 
        
        InlineObject11.initialize(this, name, lang, iso);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, name, lang, iso) { 
        obj['name'] = name;
        obj['lang'] = lang;
        obj['iso'] = iso;
    }

    /**
     * Constructs a <code>InlineObject11</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/InlineObject11} obj Optional instance to populate.
     * @return {module:model/InlineObject11} The populated <code>InlineObject11</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new InlineObject11();

            if (data.hasOwnProperty('name')) {
                obj['name'] = ApiClient.convertToType(data['name'], 'String');
            }
            if (data.hasOwnProperty('lang')) {
                obj['lang'] = ApiClient.convertToType(data['lang'], 'String');
            }
            if (data.hasOwnProperty('iso')) {
                obj['iso'] = ApiClient.convertToType(data['iso'], 'String');
            }
            if (data.hasOwnProperty('enabled')) {
                obj['enabled'] = ApiClient.convertToType(data['enabled'], 'Boolean');
            }
            if (data.hasOwnProperty('default')) {
                obj['default'] = ApiClient.convertToType(data['default'], 'Boolean');
            }
            if (data.hasOwnProperty('current')) {
                obj['current'] = ApiClient.convertToType(data['current'], 'Boolean');
            }
        }
        return obj;
    }


}

/**
 * @member {String} name
 */
InlineObject11.prototype['name'] = undefined;

/**
 * @member {String} lang
 */
InlineObject11.prototype['lang'] = undefined;

/**
 * Unique
 * @member {String} iso
 */
InlineObject11.prototype['iso'] = undefined;

/**
 * @member {Boolean} enabled
 */
InlineObject11.prototype['enabled'] = undefined;

/**
 * @member {Boolean} default
 */
InlineObject11.prototype['default'] = undefined;

/**
 * @member {Boolean} current
 */
InlineObject11.prototype['current'] = undefined;






export default InlineObject11;

