/**
 * GetCandy
 * The GetCandy API
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@getcandy.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The Layout model module.
 * @module model/Layout
 * @version 0.9.0
 */
class Layout {
    /**
     * Constructs a new <code>Layout</code>.
     * @alias module:model/Layout
     * @param id {String} 
     * @param name {String} 
     * @param handle {String} 
     * @param type {String} 
     */
    constructor(id, name, handle, type) { 
        
        Layout.initialize(this, id, name, handle, type);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, id, name, handle, type) { 
        obj['id'] = id;
        obj['name'] = name;
        obj['handle'] = handle;
        obj['type'] = type;
    }

    /**
     * Constructs a <code>Layout</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/Layout} obj Optional instance to populate.
     * @return {module:model/Layout} The populated <code>Layout</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new Layout();

            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'String');
            }
            if (data.hasOwnProperty('name')) {
                obj['name'] = ApiClient.convertToType(data['name'], 'String');
            }
            if (data.hasOwnProperty('handle')) {
                obj['handle'] = ApiClient.convertToType(data['handle'], 'String');
            }
            if (data.hasOwnProperty('type')) {
                obj['type'] = ApiClient.convertToType(data['type'], 'String');
            }
        }
        return obj;
    }


}

/**
 * @member {String} id
 */
Layout.prototype['id'] = undefined;

/**
 * @member {String} name
 */
Layout.prototype['name'] = undefined;

/**
 * @member {String} handle
 */
Layout.prototype['handle'] = undefined;

/**
 * @member {String} type
 */
Layout.prototype['type'] = undefined;






export default Layout;

