/**
 * GetCandy
 * The GetCandy API
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@getcandy.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import OrderType from './OrderType';

/**
 * The OrderTypeCollection model module.
 * @module model/OrderTypeCollection
 * @version 0.9.0
 */
class OrderTypeCollection {
    /**
     * Constructs a new <code>OrderTypeCollection</code>.
     * @alias module:model/OrderTypeCollection
     */
    constructor() { 
        
        OrderTypeCollection.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>OrderTypeCollection</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/OrderTypeCollection} obj Optional instance to populate.
     * @return {module:model/OrderTypeCollection} The populated <code>OrderTypeCollection</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new OrderTypeCollection();

            if (data.hasOwnProperty('data')) {
                obj['data'] = ApiClient.convertToType(data['data'], [OrderType]);
            }
        }
        return obj;
    }


}

/**
 * @member {Array.<module:model/OrderType>} data
 */
OrderTypeCollection.prototype['data'] = undefined;






export default OrderTypeCollection;

