/**
 * GetCandy
 * The GetCandy API
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import ProductAssociation from './ProductAssociation';

/**
 * The ProductAssociationCollection model module.
 * @module model/ProductAssociationCollection
 * @version 1.0.0
 */
class ProductAssociationCollection {
    /**
     * Constructs a new <code>ProductAssociationCollection</code>.
     * @alias module:model/ProductAssociationCollection
     */
    constructor() { 
        
        ProductAssociationCollection.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>ProductAssociationCollection</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/ProductAssociationCollection} obj Optional instance to populate.
     * @return {module:model/ProductAssociationCollection} The populated <code>ProductAssociationCollection</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new ProductAssociationCollection();

            if (data.hasOwnProperty('data')) {
                obj['data'] = ApiClient.convertToType(data['data'], [ProductAssociation]);
            }
        }
        return obj;
    }


}

/**
 * @member {Array.<module:model/ProductAssociation>} data
 */
ProductAssociationCollection.prototype['data'] = undefined;






export default ProductAssociationCollection;

