/**
 * GetCandy
 * The GetCandy API
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import CustomerGroupResponse from './CustomerGroupResponse';

/**
 * The ProductTierPrice model module.
 * @module model/ProductTierPrice
 * @version 1.0.0
 */
class ProductTierPrice {
    /**
     * Constructs a new <code>ProductTierPrice</code>.
     * @alias module:model/ProductTierPrice
     */
    constructor() { 
        
        ProductTierPrice.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>ProductTierPrice</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/ProductTierPrice} obj Optional instance to populate.
     * @return {module:model/ProductTierPrice} The populated <code>ProductTierPrice</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new ProductTierPrice();

            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'String');
            }
            if (data.hasOwnProperty('lower_limit')) {
                obj['lower_limit'] = ApiClient.convertToType(data['lower_limit'], 'Number');
            }
            if (data.hasOwnProperty('price')) {
                obj['price'] = ApiClient.convertToType(data['price'], 'Number');
            }
            if (data.hasOwnProperty('tax')) {
                obj['tax'] = ApiClient.convertToType(data['tax'], 'Number');
            }
            if (data.hasOwnProperty('group')) {
                obj['group'] = CustomerGroupResponse.constructFromObject(data['group']);
            }
        }
        return obj;
    }


}

/**
 * @member {String} id
 */
ProductTierPrice.prototype['id'] = undefined;

/**
 * @member {Number} lower_limit
 */
ProductTierPrice.prototype['lower_limit'] = undefined;

/**
 * @member {Number} price
 */
ProductTierPrice.prototype['price'] = undefined;

/**
 * @member {Number} tax
 */
ProductTierPrice.prototype['tax'] = undefined;

/**
 * @member {module:model/CustomerGroupResponse} group
 */
ProductTierPrice.prototype['group'] = undefined;






export default ProductTierPrice;

