/**
 * GetCandy
 * The GetCandy API
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The ProductsProductIdDuplicateRoutes model module.
 * @module model/ProductsProductIdDuplicateRoutes
 * @version 1.0.0
 */
class ProductsProductIdDuplicateRoutes {
    /**
     * Constructs a new <code>ProductsProductIdDuplicateRoutes</code>.
     * @alias module:model/ProductsProductIdDuplicateRoutes
     */
    constructor() { 
        
        ProductsProductIdDuplicateRoutes.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>ProductsProductIdDuplicateRoutes</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/ProductsProductIdDuplicateRoutes} obj Optional instance to populate.
     * @return {module:model/ProductsProductIdDuplicateRoutes} The populated <code>ProductsProductIdDuplicateRoutes</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new ProductsProductIdDuplicateRoutes();

            if (data.hasOwnProperty('old')) {
                obj['old'] = ApiClient.convertToType(data['old'], 'String');
            }
            if (data.hasOwnProperty('new')) {
                obj['new'] = ApiClient.convertToType(data['new'], 'String');
            }
        }
        return obj;
    }


}

/**
 * @member {String} old
 */
ProductsProductIdDuplicateRoutes.prototype['old'] = undefined;

/**
 * @member {String} new
 */
ProductsProductIdDuplicateRoutes.prototype['new'] = undefined;






export default ProductsProductIdDuplicateRoutes;

