/**
 * GetCandy
 * The GetCandy API
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import ProductAssociation from './ProductAssociation';

/**
 * The ProductAssociationResponse model module.
 * @module model/ProductAssociationResponse
 * @version 1.0.0
 */
class ProductAssociationResponse {
    /**
     * Constructs a new <code>ProductAssociationResponse</code>.
     * @alias module:model/ProductAssociationResponse
     */
    constructor() { 
        
        ProductAssociationResponse.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>ProductAssociationResponse</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/ProductAssociationResponse} obj Optional instance to populate.
     * @return {module:model/ProductAssociationResponse} The populated <code>ProductAssociationResponse</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new ProductAssociationResponse();

            if (data.hasOwnProperty('data')) {
                obj['data'] = ProductAssociation.constructFromObject(data['data']);
            }
        }
        return obj;
    }


}

/**
 * @member {module:model/ProductAssociation} data
 */
ProductAssociationResponse.prototype['data'] = undefined;






export default ProductAssociationResponse;

