/**
 * GetCandy
 * The GetCandy API
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@getcandy.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import AssetResponse from './AssetResponse';
import CustomerPriceCollection from './CustomerPriceCollection';
import ProductResponse from './ProductResponse';
import ProductTierPriceCollection from './ProductTierPriceCollection';
import ProductVariantWeight from './ProductVariantWeight';
import TaxResponse from './TaxResponse';

/**
 * The ProductVariant model module.
 * @module model/ProductVariant
 * @version 0.9.0
 */
class ProductVariant {
    /**
     * Constructs a new <code>ProductVariant</code>.
     * ### Available includes  - products - basketLines - image - tax - customerPricing - tiers
     * @alias module:model/ProductVariant
     */
    constructor() { 
        
        ProductVariant.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>ProductVariant</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/ProductVariant} obj Optional instance to populate.
     * @return {module:model/ProductVariant} The populated <code>ProductVariant</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new ProductVariant();

            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'String');
            }
            if (data.hasOwnProperty('sku')) {
                obj['sku'] = ApiClient.convertToType(data['sku'], 'String');
            }
            if (data.hasOwnProperty('backorder')) {
                obj['backorder'] = ApiClient.convertToType(data['backorder'], 'String');
            }
            if (data.hasOwnProperty('requires_shipping')) {
                obj['requires_shipping'] = ApiClient.convertToType(data['requires_shipping'], 'Boolean');
            }
            if (data.hasOwnProperty('price')) {
                obj['price'] = ApiClient.convertToType(data['price'], 'Number');
            }
            if (data.hasOwnProperty('factor_tax')) {
                obj['factor_tax'] = ApiClient.convertToType(data['factor_tax'], 'Number');
            }
            if (data.hasOwnProperty('unit_price')) {
                obj['unit_price'] = ApiClient.convertToType(data['unit_price'], 'Number');
            }
            if (data.hasOwnProperty('total_tax')) {
                obj['total_tax'] = ApiClient.convertToType(data['total_tax'], 'Number');
            }
            if (data.hasOwnProperty('unit_tax')) {
                obj['unit_tax'] = ApiClient.convertToType(data['unit_tax'], 'Number');
            }
            if (data.hasOwnProperty('unit_qty')) {
                obj['unit_qty'] = ApiClient.convertToType(data['unit_qty'], 'Number');
            }
            if (data.hasOwnProperty('min_qty')) {
                obj['min_qty'] = ApiClient.convertToType(data['min_qty'], 'Number');
            }
            if (data.hasOwnProperty('max_qty')) {
                obj['max_qty'] = ApiClient.convertToType(data['max_qty'], 'Number');
            }
            if (data.hasOwnProperty('min_batch')) {
                obj['min_batch'] = ApiClient.convertToType(data['min_batch'], 'Number');
            }
            if (data.hasOwnProperty('inventory')) {
                obj['inventory'] = ApiClient.convertToType(data['inventory'], 'Number');
            }
            if (data.hasOwnProperty('incoming')) {
                obj['incoming'] = ApiClient.convertToType(data['incoming'], 'Number');
            }
            if (data.hasOwnProperty('group_pricing')) {
                obj['group_pricing'] = ApiClient.convertToType(data['group_pricing'], 'Boolean');
            }
            if (data.hasOwnProperty('weight')) {
                obj['weight'] = ProductVariantWeight.constructFromObject(data['weight']);
            }
            if (data.hasOwnProperty('height')) {
                obj['height'] = ProductVariantWeight.constructFromObject(data['height']);
            }
            if (data.hasOwnProperty('width')) {
                obj['width'] = ProductVariantWeight.constructFromObject(data['width']);
            }
            if (data.hasOwnProperty('depth')) {
                obj['depth'] = ProductVariantWeight.constructFromObject(data['depth']);
            }
            if (data.hasOwnProperty('volume')) {
                obj['volume'] = ProductVariantWeight.constructFromObject(data['volume']);
            }
            if (data.hasOwnProperty('product')) {
                obj['product'] = ProductResponse.constructFromObject(data['product']);
            }
            if (data.hasOwnProperty('image')) {
                obj['image'] = AssetResponse.constructFromObject(data['image']);
            }
            if (data.hasOwnProperty('customer_pricing')) {
                obj['customer_pricing'] = CustomerPriceCollection.constructFromObject(data['customer_pricing']);
            }
            if (data.hasOwnProperty('tax')) {
                obj['tax'] = TaxResponse.constructFromObject(data['tax']);
            }
            if (data.hasOwnProperty('tiers')) {
                obj['tiers'] = ProductTierPriceCollection.constructFromObject(data['tiers']);
            }
            if (data.hasOwnProperty('options')) {
                obj['options'] = ApiClient.convertToType(data['options'], Object);
            }
        }
        return obj;
    }


}

/**
 * @member {String} id
 */
ProductVariant.prototype['id'] = undefined;

/**
 * @member {String} sku
 */
ProductVariant.prototype['sku'] = undefined;

/**
 * @member {String} backorder
 */
ProductVariant.prototype['backorder'] = undefined;

/**
 * @member {Boolean} requires_shipping
 */
ProductVariant.prototype['requires_shipping'] = undefined;

/**
 * @member {Number} price
 */
ProductVariant.prototype['price'] = undefined;

/**
 * @member {Number} factor_tax
 */
ProductVariant.prototype['factor_tax'] = undefined;

/**
 * @member {Number} unit_price
 */
ProductVariant.prototype['unit_price'] = undefined;

/**
 * @member {Number} total_tax
 */
ProductVariant.prototype['total_tax'] = undefined;

/**
 * @member {Number} unit_tax
 */
ProductVariant.prototype['unit_tax'] = undefined;

/**
 * @member {Number} unit_qty
 */
ProductVariant.prototype['unit_qty'] = undefined;

/**
 * @member {Number} min_qty
 */
ProductVariant.prototype['min_qty'] = undefined;

/**
 * @member {Number} max_qty
 */
ProductVariant.prototype['max_qty'] = undefined;

/**
 * @member {Number} min_batch
 */
ProductVariant.prototype['min_batch'] = undefined;

/**
 * @member {Number} inventory
 */
ProductVariant.prototype['inventory'] = undefined;

/**
 * @member {Number} incoming
 */
ProductVariant.prototype['incoming'] = undefined;

/**
 * @member {Boolean} group_pricing
 */
ProductVariant.prototype['group_pricing'] = undefined;

/**
 * @member {module:model/ProductVariantWeight} weight
 */
ProductVariant.prototype['weight'] = undefined;

/**
 * @member {module:model/ProductVariantWeight} height
 */
ProductVariant.prototype['height'] = undefined;

/**
 * @member {module:model/ProductVariantWeight} width
 */
ProductVariant.prototype['width'] = undefined;

/**
 * @member {module:model/ProductVariantWeight} depth
 */
ProductVariant.prototype['depth'] = undefined;

/**
 * @member {module:model/ProductVariantWeight} volume
 */
ProductVariant.prototype['volume'] = undefined;

/**
 * @member {module:model/ProductResponse} product
 */
ProductVariant.prototype['product'] = undefined;

/**
 * @member {module:model/AssetResponse} image
 */
ProductVariant.prototype['image'] = undefined;

/**
 * @member {module:model/CustomerPriceCollection} customer_pricing
 */
ProductVariant.prototype['customer_pricing'] = undefined;

/**
 * @member {module:model/TaxResponse} tax
 */
ProductVariant.prototype['tax'] = undefined;

/**
 * @member {module:model/ProductTierPriceCollection} tiers
 */
ProductVariant.prototype['tiers'] = undefined;

/**
 * @member {Object} options
 */
ProductVariant.prototype['options'] = undefined;






export default ProductVariant;

