/**
 * GetCandy
 * The GetCandy API
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@getcandy.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import AttributeCollection from './AttributeCollection';

/**
 * The ProductFamily model module.
 * @module model/ProductFamily
 * @version 0.9.0
 */
class ProductFamily {
    /**
     * Constructs a new <code>ProductFamily</code>.
     * @alias module:model/ProductFamily
     */
    constructor() { 
        
        ProductFamily.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>ProductFamily</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/ProductFamily} obj Optional instance to populate.
     * @return {module:model/ProductFamily} The populated <code>ProductFamily</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new ProductFamily();

            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'String');
            }
            if (data.hasOwnProperty('name')) {
                obj['name'] = ApiClient.convertToType(data['name'], 'String');
            }
            if (data.hasOwnProperty('attributes')) {
                obj['attributes'] = AttributeCollection.constructFromObject(data['attributes']);
            }
        }
        return obj;
    }


}

/**
 * @member {String} id
 */
ProductFamily.prototype['id'] = undefined;

/**
 * @member {String} name
 */
ProductFamily.prototype['name'] = undefined;

/**
 * @member {module:model/AttributeCollection} attributes
 */
ProductFamily.prototype['attributes'] = undefined;






export default ProductFamily;

