/**
 * GetCandy
 * The GetCandy API
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import BasketResponse from './BasketResponse';

/**
 * The SavedBasket model module.
 * @module model/SavedBasket
 * @version 1.0.0
 */
class SavedBasket {
    /**
     * Constructs a new <code>SavedBasket</code>.
     * @alias module:model/SavedBasket
     */
    constructor() { 
        
        SavedBasket.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>SavedBasket</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/SavedBasket} obj Optional instance to populate.
     * @return {module:model/SavedBasket} The populated <code>SavedBasket</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new SavedBasket();

            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'String');
            }
            if (data.hasOwnProperty('name')) {
                obj['name'] = ApiClient.convertToType(data['name'], 'String');
            }
            if (data.hasOwnProperty('basket')) {
                obj['basket'] = BasketResponse.constructFromObject(data['basket']);
            }
        }
        return obj;
    }


}

/**
 * @member {String} id
 */
SavedBasket.prototype['id'] = undefined;

/**
 * @member {String} name
 */
SavedBasket.prototype['name'] = undefined;

/**
 * @member {module:model/BasketResponse} basket
 */
SavedBasket.prototype['basket'] = undefined;






export default SavedBasket;

