/**
 * GetCandy
 * The GetCandy API
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import SearchMeta from './SearchMeta';

/**
 * The Search model module.
 * @module model/Search
 * @version 1.0.0
 */
class Search {
    /**
     * Constructs a new <code>Search</code>.
     * @alias module:model/Search
     */
    constructor() { 
        
        Search.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>Search</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/Search} obj Optional instance to populate.
     * @return {module:model/Search} The populated <code>Search</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new Search();

            if (data.hasOwnProperty('suggestions')) {
                obj['suggestions'] = ApiClient.convertToType(data['suggestions'], Object);
            }
            if (data.hasOwnProperty('meta')) {
                obj['meta'] = SearchMeta.constructFromObject(data['meta']);
            }
            if (data.hasOwnProperty('data')) {
                obj['data'] = ApiClient.convertToType(data['data'], [Object]);
            }
        }
        return obj;
    }


}

/**
 * @member {Object} suggestions
 */
Search.prototype['suggestions'] = undefined;

/**
 * @member {module:model/SearchMeta} meta
 */
Search.prototype['meta'] = undefined;

/**
 * @member {Array.<Object>} data
 */
Search.prototype['data'] = undefined;






export default Search;

