/**
 * GetCandy
 * The GetCandy API
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import Setting from './Setting';

/**
 * The SettingCollection model module.
 * @module model/SettingCollection
 * @version 1.0.0
 */
class SettingCollection {
    /**
     * Constructs a new <code>SettingCollection</code>.
     * @alias module:model/SettingCollection
     */
    constructor() { 
        
        SettingCollection.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>SettingCollection</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/SettingCollection} obj Optional instance to populate.
     * @return {module:model/SettingCollection} The populated <code>SettingCollection</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new SettingCollection();

            if (data.hasOwnProperty('data')) {
                obj['data'] = ApiClient.convertToType(data['data'], [Setting]);
            }
        }
        return obj;
    }


}

/**
 * @member {Array.<module:model/Setting>} data
 */
SettingCollection.prototype['data'] = undefined;






export default SettingCollection;

