/**
 * GetCandy
 * The GetCandy API
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@getcandy.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import ShippingPrice from './ShippingPrice';

/**
 * The ShippingPriceResponse model module.
 * @module model/ShippingPriceResponse
 * @version 0.9.0
 */
class ShippingPriceResponse {
    /**
     * Constructs a new <code>ShippingPriceResponse</code>.
     * @alias module:model/ShippingPriceResponse
     */
    constructor() { 
        
        ShippingPriceResponse.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>ShippingPriceResponse</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/ShippingPriceResponse} obj Optional instance to populate.
     * @return {module:model/ShippingPriceResponse} The populated <code>ShippingPriceResponse</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new ShippingPriceResponse();

            if (data.hasOwnProperty('data')) {
                obj['data'] = ShippingPrice.constructFromObject(data['data']);
            }
        }
        return obj;
    }


}

/**
 * @member {module:model/ShippingPrice} data
 */
ShippingPriceResponse.prototype['data'] = undefined;






export default ShippingPriceResponse;

