/**
 * GetCandy
 * The GetCandy API
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import Links from './Links';
import PaginatedResponse from './PaginatedResponse';
import Pagination from './Pagination';
import Tax from './Tax';
import TaxCollectionAllOf from './TaxCollectionAllOf';

/**
 * The TaxCollection model module.
 * @module model/TaxCollection
 * @version 1.0.0
 */
class TaxCollection {
    /**
     * Constructs a new <code>TaxCollection</code>.
     * @alias module:model/TaxCollection
     * @extends module:model/PaginatedResponse
     * @implements module:model/TaxCollectionAllOf
     * @implements module:model/PaginatedResponse
     */
    constructor() { 
        TaxCollectionAllOf.initialize(this);PaginatedResponse.initialize(this);
        TaxCollection.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>TaxCollection</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/TaxCollection} obj Optional instance to populate.
     * @return {module:model/TaxCollection} The populated <code>TaxCollection</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new TaxCollection();
            PaginatedResponse.constructFromObject(data, obj);
            TaxCollectionAllOf.constructFromObject(data, obj);
            PaginatedResponse.constructFromObject(data, obj);

            if (data.hasOwnProperty('data')) {
                obj['data'] = ApiClient.convertToType(data['data'], [Tax]);
            }
        }
        return obj;
    }


}

/**
 * @member {Array.<module:model/Tax>} data
 */
TaxCollection.prototype['data'] = undefined;


// Implement TaxCollectionAllOf interface:
/**
 * @member {Array.<module:model/Tax>} data
 */
TaxCollectionAllOf.prototype['data'] = undefined;
// Implement PaginatedResponse interface:
/**
 * @member {module:model/Links} links
 */
PaginatedResponse.prototype['links'] = undefined;
/**
 * @member {module:model/Pagination} meta
 */
PaginatedResponse.prototype['meta'] = undefined;




export default TaxCollection;

