/**
 * GetCandy
 * The GetCandy API
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@getcandy.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */


import ApiClient from "../ApiClient";
import LayoutCollection from '../model/LayoutCollection';

/**
* Layouts service.
* @module api/LayoutsApi
* @version 0.9.0
*/
export default class LayoutsApi {

    /**
    * Constructs a new LayoutsApi. 
    * @alias module:api/LayoutsApi
    * @class
    * @param {module:ApiClient} [apiClient] Optional API client implementation to use,
    * default to {@link module:ApiClient#instance} if unspecified.
    */
    constructor(apiClient) {
        this.apiClient = apiClient || ApiClient.instance;
    }



    /**
     * Get Layouts
     * Get a paginated list of Layouts
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing data of type {@link module:model/LayoutCollection} and HTTP response
     */
    getLayoutsWithHttpInfo() {
      let postBody = null;

      let pathParams = {
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['auth'];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = LayoutCollection;
      return this.apiClient.callApi(
        '/layouts', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null
      );
    }

    /**
     * Get Layouts
     * Get a paginated list of Layouts
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with data of type {@link module:model/LayoutCollection}
     */
    getLayouts() {
      return this.getLayoutsWithHttpInfo()
        .then(function(response_and_data) {
          return response_and_data.data;
        });
    }


}
