/**
 * GetCandy
 * The GetCandy API
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.GetcandyJs);
  }
}(this, function(expect, GetcandyJs) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new GetcandyJs.BasketLine();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('BasketLine', function() {
    it('should create an instance of BasketLine', function() {
      // uncomment below and update the code to test BasketLine
      //var instane = new GetcandyJs.BasketLine();
      //expect(instance).to.be.a(GetcandyJs.BasketLine);
    });

    it('should have the property id (base name: "id")', function() {
      // uncomment below and update the code to test the property id
      //var instane = new GetcandyJs.BasketLine();
      //expect(instance).to.be();
    });

    it('should have the property quantity (base name: "quantity")', function() {
      // uncomment below and update the code to test the property quantity
      //var instane = new GetcandyJs.BasketLine();
      //expect(instance).to.be();
    });

    it('should have the property lineTotal (base name: "line_total")', function() {
      // uncomment below and update the code to test the property lineTotal
      //var instane = new GetcandyJs.BasketLine();
      //expect(instance).to.be();
    });

    it('should have the property unitPrice (base name: "unit_price")', function() {
      // uncomment below and update the code to test the property unitPrice
      //var instane = new GetcandyJs.BasketLine();
      //expect(instance).to.be();
    });

    it('should have the property unitTax (base name: "unit_tax")', function() {
      // uncomment below and update the code to test the property unitTax
      //var instane = new GetcandyJs.BasketLine();
      //expect(instance).to.be();
    });

    it('should have the property lineDiscount (base name: "line_discount")', function() {
      // uncomment below and update the code to test the property lineDiscount
      //var instane = new GetcandyJs.BasketLine();
      //expect(instance).to.be();
    });

    it('should have the property tax (base name: "tax")', function() {
      // uncomment below and update the code to test the property tax
      //var instane = new GetcandyJs.BasketLine();
      //expect(instance).to.be();
    });

    it('should have the property meta (base name: "meta")', function() {
      // uncomment below and update the code to test the property meta
      //var instane = new GetcandyJs.BasketLine();
      //expect(instance).to.be();
    });

  });

}));
