/**
 * GetCandy
 * The GetCandy API
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@getcandy.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.@GetcandyJsClient);
  }
}(this, function(expect, @GetcandyJsClient) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new @GetcandyJsClient.InlineResponse2005();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('InlineResponse2005', function() {
    it('should create an instance of InlineResponse2005', function() {
      // uncomment below and update the code to test InlineResponse2005
      //var instane = new @GetcandyJsClient.InlineResponse2005();
      //expect(instance).to.be.a(@GetcandyJsClient.InlineResponse2005);
    });

    it('should have the property currentMonth (base name: "current_month")', function() {
      // uncomment below and update the code to test the property currentMonth
      //var instane = new @GetcandyJsClient.InlineResponse2005();
      //expect(instance).to.be();
    });

    it('should have the property previousMonth (base name: "previous_month")', function() {
      // uncomment below and update the code to test the property previousMonth
      //var instane = new @GetcandyJsClient.InlineResponse2005();
      //expect(instance).to.be();
    });

    it('should have the property today (base name: "today")', function() {
      // uncomment below and update the code to test the property today
      //var instane = new @GetcandyJsClient.InlineResponse2005();
      //expect(instance).to.be();
    });

    it('should have the property yesterday (base name: "yesterday")', function() {
      // uncomment below and update the code to test the property yesterday
      //var instane = new @GetcandyJsClient.InlineResponse2005();
      //expect(instance).to.be();
    });

    it('should have the property currentWeek (base name: "current_week")', function() {
      // uncomment below and update the code to test the property currentWeek
      //var instane = new @GetcandyJsClient.InlineResponse2005();
      //expect(instance).to.be();
    });

    it('should have the property previousWeek (base name: "previous_week")', function() {
      // uncomment below and update the code to test the property previousWeek
      //var instane = new @GetcandyJsClient.InlineResponse2005();
      //expect(instance).to.be();
    });

  });

}));
