/**
 * GetCandy
 * The GetCandy API
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@getcandy.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.GetcandyJs);
  }
}(this, function(expect, GetcandyJs) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new GetcandyJs.BasketsApi();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('BasketsApi', function() {
    describe('deleteBasketLines', function() {
      it('should call deleteBasketLines successfully', function(done) {
        //uncomment below and update the code to test deleteBasketLines
        //instance.deleteBasketLines(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('deleteBasketsBasketId', function() {
      it('should call deleteBasketsBasketId successfully', function(done) {
        //uncomment below and update the code to test deleteBasketsBasketId
        //instance.deleteBasketsBasketId(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('deleteBasketsBasketIdDiscounts', function() {
      it('should call deleteBasketsBasketIdDiscounts successfully', function(done) {
        //uncomment below and update the code to test deleteBasketsBasketIdDiscounts
        //instance.deleteBasketsBasketIdDiscounts(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('deleteBasketsBasketIdUser', function() {
      it('should call deleteBasketsBasketIdUser successfully', function(done) {
        //uncomment below and update the code to test deleteBasketsBasketIdUser
        //instance.deleteBasketsBasketIdUser(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getBaskets', function() {
      it('should call getBaskets successfully', function(done) {
        //uncomment below and update the code to test getBaskets
        //instance.getBaskets(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getBasketsBasketId', function() {
      it('should call getBasketsBasketId successfully', function(done) {
        //uncomment below and update the code to test getBasketsBasketId
        //instance.getBasketsBasketId(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getBasketsCurrent', function() {
      it('should call getBasketsCurrent successfully', function(done) {
        //uncomment below and update the code to test getBasketsCurrent
        //instance.getBasketsCurrent(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getBasketsSaved', function() {
      it('should call getBasketsSaved successfully', function(done) {
        //uncomment below and update the code to test getBasketsSaved
        //instance.getBasketsSaved(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('postBasketLines', function() {
      it('should call postBasketLines successfully', function(done) {
        //uncomment below and update the code to test postBasketLines
        //instance.postBasketLines(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('postBaskets', function() {
      it('should call postBaskets successfully', function(done) {
        //uncomment below and update the code to test postBaskets
        //instance.postBaskets(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('postBasketsBasketIdClaim', function() {
      it('should call postBasketsBasketIdClaim successfully', function(done) {
        //uncomment below and update the code to test postBasketsBasketIdClaim
        //instance.postBasketsBasketIdClaim(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('postBasketsBasketIdMeta', function() {
      it('should call postBasketsBasketIdMeta successfully', function(done) {
        //uncomment below and update the code to test postBasketsBasketIdMeta
        //instance.postBasketsBasketIdMeta(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('postBasketsBasketIdSave', function() {
      it('should call postBasketsBasketIdSave successfully', function(done) {
        //uncomment below and update the code to test postBasketsBasketIdSave
        //instance.postBasketsBasketIdSave(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('postBasketsResolve', function() {
      it('should call postBasketsResolve successfully', function(done) {
        //uncomment below and update the code to test postBasketsResolve
        //instance.postBasketsResolve(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('putBasketLinesBasketLineId', function() {
      it('should call putBasketLinesBasketLineId successfully', function(done) {
        //uncomment below and update the code to test putBasketLinesBasketLineId
        //instance.putBasketLinesBasketLineId(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('putBasketLinesBasketLineIdAdd', function() {
      it('should call putBasketLinesBasketLineIdAdd successfully', function(done) {
        //uncomment below and update the code to test putBasketLinesBasketLineIdAdd
        //instance.putBasketLinesBasketLineIdAdd(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('putBasketLinesBasketLineIdRemove', function() {
      it('should call putBasketLinesBasketLineIdRemove successfully', function(done) {
        //uncomment below and update the code to test putBasketLinesBasketLineIdRemove
        //instance.putBasketLinesBasketLineIdRemove(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('putBasketsBasketId', function() {
      it('should call putBasketsBasketId successfully', function(done) {
        //uncomment below and update the code to test putBasketsBasketId
        //instance.putBasketsBasketId(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('putBasketsBasketIdUser', function() {
      it('should call putBasketsBasketIdUser successfully', function(done) {
        //uncomment below and update the code to test putBasketsBasketIdUser
        //instance.putBasketsBasketIdUser(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('putBasketsSavedBasketId', function() {
      it('should call putBasketsSavedBasketId successfully', function(done) {
        //uncomment below and update the code to test putBasketsSavedBasketId
        //instance.putBasketsSavedBasketId(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
  });

}));
