/**
 * GetCandy
 * The GetCandy API
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.GetcandyJs);
  }
}(this, function(expect, GetcandyJs) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new GetcandyJs.CollectionsApi();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('CollectionsApi', function() {
    describe('deleteCollectionsCollectionId', function() {
      it('should call deleteCollectionsCollectionId successfully', function(done) {
        //uncomment below and update the code to test deleteCollectionsCollectionId
        //instance.deleteCollectionsCollectionId(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getCollections', function() {
      it('should call getCollections successfully', function(done) {
        //uncomment below and update the code to test getCollections
        //instance.getCollections(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getCollectionsCollectionId', function() {
      it('should call getCollectionsCollectionId successfully', function(done) {
        //uncomment below and update the code to test getCollectionsCollectionId
        //instance.getCollectionsCollectionId(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('postCollections', function() {
      it('should call postCollections successfully', function(done) {
        //uncomment below and update the code to test postCollections
        //instance.postCollections(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('postCollectionsCollectionIdProducts', function() {
      it('should call postCollectionsCollectionIdProducts successfully', function(done) {
        //uncomment below and update the code to test postCollectionsCollectionIdProducts
        //instance.postCollectionsCollectionIdProducts(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('postCollectionsCollectionRoutes', function() {
      it('should call postCollectionsCollectionRoutes successfully', function(done) {
        //uncomment below and update the code to test postCollectionsCollectionRoutes
        //instance.postCollectionsCollectionRoutes(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('putCollectionsCollectionId', function() {
      it('should call putCollectionsCollectionId successfully', function(done) {
        //uncomment below and update the code to test putCollectionsCollectionId
        //instance.putCollectionsCollectionId(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
  });

}));
