/**
 * GetCandy
 * The GetCandy API
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.GetcandyJs);
  }
}(this, function(expect, GetcandyJs) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new GetcandyJs.OrdersApi();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('OrdersApi', function() {
    describe('deleteOrdersLinesOrderId', function() {
      it('should call deleteOrdersLinesOrderId successfully', function(done) {
        //uncomment below and update the code to test deleteOrdersLinesOrderId
        //instance.deleteOrdersLinesOrderId(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getOrders', function() {
      it('should call getOrders successfully', function(done) {
        //uncomment below and update the code to test getOrders
        //instance.getOrders(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getOrdersBulk', function() {
      it('should call getOrdersBulk successfully', function(done) {
        //uncomment below and update the code to test getOrdersBulk
        //instance.getOrdersBulk(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getOrdersEmailPreviewStatus', function() {
      it('should call getOrdersEmailPreviewStatus successfully', function(done) {
        //uncomment below and update the code to test getOrdersEmailPreviewStatus
        //instance.getOrdersEmailPreviewStatus(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getOrdersIdInvoice', function() {
      it('should call getOrdersIdInvoice successfully', function(done) {
        //uncomment below and update the code to test getOrdersIdInvoice
        //instance.getOrdersIdInvoice(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getOrdersIdShippingMethods', function() {
      it('should call getOrdersIdShippingMethods successfully', function(done) {
        //uncomment below and update the code to test getOrdersIdShippingMethods
        //instance.getOrdersIdShippingMethods(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getOrdersOrderId', function() {
      it('should call getOrdersOrderId successfully', function(done) {
        //uncomment below and update the code to test getOrdersOrderId
        //instance.getOrdersOrderId(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getOrdersTypes', function() {
      it('should call getOrdersTypes successfully', function(done) {
        //uncomment below and update the code to test getOrdersTypes
        //instance.getOrdersTypes(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('postOrders', function() {
      it('should call postOrders successfully', function(done) {
        //uncomment below and update the code to test postOrders
        //instance.postOrders(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('postOrdersBulk', function() {
      it('should call postOrdersBulk successfully', function(done) {
        //uncomment below and update the code to test postOrdersBulk
        //instance.postOrdersBulk(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('postOrdersOrderIdExpire', function() {
      it('should call postOrdersOrderIdExpire successfully', function(done) {
        //uncomment below and update the code to test postOrdersOrderIdExpire
        //instance.postOrdersOrderIdExpire(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('postOrdersProcess', function() {
      it('should call postOrdersProcess successfully', function(done) {
        //uncomment below and update the code to test postOrdersProcess
        //instance.postOrdersProcess(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('putOrdersIdContact', function() {
      it('should call putOrdersIdContact successfully', function(done) {
        //uncomment below and update the code to test putOrdersIdContact
        //instance.putOrdersIdContact(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('putOrdersIdLines', function() {
      it('should call putOrdersIdLines successfully', function(done) {
        //uncomment below and update the code to test putOrdersIdLines
        //instance.putOrdersIdLines(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('putOrdersIdShippingAddress', function() {
      it('should call putOrdersIdShippingAddress successfully', function(done) {
        //uncomment below and update the code to test putOrdersIdShippingAddress
        //instance.putOrdersIdShippingAddress(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('putOrdersIdShippingCost', function() {
      it('should call putOrdersIdShippingCost successfully', function(done) {
        //uncomment below and update the code to test putOrdersIdShippingCost
        //instance.putOrdersIdShippingCost(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('putOrdersOrderId', function() {
      it('should call putOrdersOrderId successfully', function(done) {
        //uncomment below and update the code to test putOrdersOrderId
        //instance.putOrdersOrderId(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('putOrdersOrderIdBillingAddress', function() {
      it('should call putOrdersOrderIdBillingAddress successfully', function(done) {
        //uncomment below and update the code to test putOrdersOrderIdBillingAddress
        //instance.putOrdersOrderIdBillingAddress(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
  });

}));
