/**
 * GetCandy
 * The GetCandy API
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.GetcandyJs);
  }
}(this, function(expect, GetcandyJs) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new GetcandyJs.ReportsApi();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('ReportsApi', function() {
    describe('getProductsBestSellers', function() {
      it('should call getProductsBestSellers successfully', function(done) {
        //uncomment below and update the code to test getProductsBestSellers
        //instance.getProductsBestSellers(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getReportsMetricsSubject', function() {
      it('should call getReportsMetricsSubject successfully', function(done) {
        //uncomment below and update the code to test getReportsMetricsSubject
        //instance.getReportsMetricsSubject(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getReportsOrders', function() {
      it('should call getReportsOrders successfully', function(done) {
        //uncomment below and update the code to test getReportsOrders
        //instance.getReportsOrders(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getReportsOrdersAverages', function() {
      it('should call getReportsOrdersAverages successfully', function(done) {
        //uncomment below and update the code to test getReportsOrdersAverages
        //instance.getReportsOrdersAverages(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getReportsOrdersCustomers', function() {
      it('should call getReportsOrdersCustomers successfully', function(done) {
        //uncomment below and update the code to test getReportsOrdersCustomers
        //instance.getReportsOrdersCustomers(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getReportsSales', function() {
      it('should call getReportsSales successfully', function(done) {
        //uncomment below and update the code to test getReportsSales
        //instance.getReportsSales(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
  });

}));
