// tslint:disable
/**
 * GetCandy
 * The GetCandy API
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@getcandy.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface AttachCategoryCustomerGroupsBodyGroups
 */
export interface AttachCategoryCustomerGroupsBodyGroups {
    /**
     * 
     * @type {string}
     * @memberof AttachCategoryCustomerGroupsBodyGroups
     */
    id?: string;
    /**
     * 
     * @type {boolean}
     * @memberof AttachCategoryCustomerGroupsBodyGroups
     */
    visible?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof AttachCategoryCustomerGroupsBodyGroups
     */
    purchasable?: boolean;
}


