// tslint:disable
/**
 * GetCandy
 * The GetCandy API
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@getcandy.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { AssociationGroupCollectionAllOf1 } from './association-group-collection-all-of1';
import { Customer } from './customer';
import { CustomerCollectionAllOf } from './customer-collection-all-of';
import { Pagination } from './pagination';

/**
 * @type CustomerCollection
 * 
 * @export
 */
export type CustomerCollection = AssociationGroupCollectionAllOf1 & CustomerCollectionAllOf;



