// tslint:disable
/**
 * GetCandy
 * The GetCandy API
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@getcandy.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { DiscountsDiscountIdSetsItems } from './discounts-discount-id-sets-items';

/**
 * 
 * @export
 * @interface DiscountsDiscountIdSetsData
 */
export interface DiscountsDiscountIdSetsData {
    /**
     * 
     * @type {string}
     * @memberof DiscountsDiscountIdSetsData
     */
    scope?: string;
    /**
     * 
     * @type {boolean}
     * @memberof DiscountsDiscountIdSetsData
     */
    outcome?: boolean;
    /**
     * 
     * @type {DiscountsDiscountIdSetsItems}
     * @memberof DiscountsDiscountIdSetsData
     */
    items?: DiscountsDiscountIdSetsItems;
}


