// tslint:disable
/**
 * GetCandy
 * The GetCandy API
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@getcandy.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { DiscountsDiscountIdChannelsData } from './discounts-discount-id-channels-data';

/**
 * 
 * @export
 * @interface DiscountsDiscountIdChannels
 */
export interface DiscountsDiscountIdChannels {
    /**
     * 
     * @type {DiscountsDiscountIdChannelsData}
     * @memberof DiscountsDiscountIdChannels
     */
    data?: DiscountsDiscountIdChannelsData;
}


