// tslint:disable
/**
 * GetCandy
 * The GetCandy API
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@getcandy.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface DiscountsDiscountIdRewardsDataProducts
 */
export interface DiscountsDiscountIdRewardsDataProducts {
    /**
     * 
     * @type {string}
     * @memberof DiscountsDiscountIdRewardsDataProducts
     */
    product_id?: string;
    /**
     * 
     * @type {number}
     * @memberof DiscountsDiscountIdRewardsDataProducts
     */
    quantity?: number;
}


