// tslint:disable
/**
 * GetCandy
 * The GetCandy API
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@getcandy.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { AssociationGroupCollectionAllOf1 } from './association-group-collection-all-of1';
import { Pagination } from './pagination';
import { PaymentType } from './payment-type';
import { PaymentTypeCollectionAllOf } from './payment-type-collection-all-of';

/**
 * @type PaymentTypeCollection
 * @export
 */
export type PaymentTypeCollection = AssociationGroupCollectionAllOf1 & PaymentTypeCollectionAllOf;



