// tslint:disable
/**
 * GetCandy
 * The GetCandy API
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@getcandy.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface ProductVariantsCreateBodyVariants
 */
export interface ProductVariantsCreateBodyVariants {
    /**
     * 
     * @type {string}
     * @memberof ProductVariantsCreateBodyVariants
     */
    label?: string;
    /**
     * 
     * @type {string}
     * @memberof ProductVariantsCreateBodyVariants
     */
    price?: string;
    /**
     * 
     * @type {string}
     * @memberof ProductVariantsCreateBodyVariants
     */
    sku?: string;
    /**
     * 
     * @type {number}
     * @memberof ProductVariantsCreateBodyVariants
     */
    inventory?: number;
}


