// tslint:disable
/**
 * GetCandy
 * The GetCandy API
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@getcandy.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { RecycleBin } from './recycle-bin';

/**
 * 
 * @export
 * @interface RecycleBinCollectionAllOf
 */
export interface RecycleBinCollectionAllOf {
    /**
     * 
     * @type {Array<RecycleBin>}
     * @memberof RecycleBinCollectionAllOf
     */
    data?: Array<RecycleBin>;
}


