// tslint:disable
/**
 * GetCandy
 * The GetCandy API
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@getcandy.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface Route
 */
export interface Route {
    /**
     * 
     * @type {string}
     * @memberof Route
     */
    id?: string;
    /**
     * 
     * @type {string}
     * @memberof Route
     */
    element_type?: string;
    /**
     * 
     * @type {number}
     * @memberof Route
     */
    element_id?: number;
    /**
     * 
     * @type {boolean}
     * @memberof Route
     */
    _default?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof Route
     */
    redirect?: boolean;
    /**
     * 
     * @type {string}
     * @memberof Route
     */
    slug?: string;
    /**
     * 
     * @type {string}
     * @memberof Route
     */
    path?: string | null;
    /**
     * 
     * @type {string}
     * @memberof Route
     */
    locale?: string;
    /**
     * 
     * @type {string}
     * @memberof Route
     */
    description?: string | null;
    /**
     * 
     * @type {string}
     * @memberof Route
     */
    drafted_at?: string;
    /**
     * 
     * @type {number}
     * @memberof Route
     */
    draft_parent_id?: number;
}


