// tslint:disable
/**
 * GetCandy
 * The GetCandy API
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@getcandy.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface SavedSearch
 */
export interface SavedSearch {
    /**
     * 
     * @type {string}
     * @memberof SavedSearch
     */
    id?: string;
    /**
     * 
     * @type {string}
     * @memberof SavedSearch
     */
    name?: string;
    /**
     * 
     * @type {object}
     * @memberof SavedSearch
     */
    payload?: object;
}


