// tslint:disable
/**
 * GetCandy
 * The GetCandy API
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@getcandy.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface UpdateCountryBody
 */
export interface UpdateCountryBody {
    /**
     * 
     * @type {boolean}
     * @memberof UpdateCountryBody
     */
    preferred?: boolean | null;
    /**
     * 
     * @type {boolean}
     * @memberof UpdateCountryBody
     */
    enabled?: boolean | null;
}


